//***********************************************************************/
//    Author                    : tywind
//    Original Date             : 15 MAY,2016
//    Module Name               : Telnet.H
//    Module Funciton           : 
//    Description               : Header file of telnet application.
//    Last modified Author      :
//    Last modified Date        : 
//    Last modified Content     :
//                                1.
//                                2.
//    Lines number              :
//    Extra comment             : 
//***********************************************************************/

#ifndef __TELNET_H__
#define __TELNET_H__

//Main entry of telnet application.
DWORD TelnetEntry(LPVOID);


#endif //__TELNET_H__
